export const defaultFormData = {
    Rank: '',
    Gender: 'Male',
    Caste: 'OPEN',
    EWS: 'No',
    PWD: 'No',
    DEF: 'No',
    TFWS: 'No',
    ORPHAN: 'No',
    MI: 'No',
    HomeUniversity: '',
    PrefferedDistrict: [],
    PrefferedBranch: [],
  }

  export const universityList = [
    'Savitribai Phule Pune University', 
    'Kavayitri Bahinabai Chaudhari North Maharashtra University, Jalgaon', 
    'Shivaji University', 
    'Sant Gadge Baba Amravati University',
    'Deemed to be University', 
    'Swami Ramanand Teerth Marathwada University, Nanded', 
    'Mumbai University', 
    'Dr. Babasaheb Ambedkar Marathwada University', 
    'Dr. Babasaheb Ambedkar Technological University,Lonere', 
    'Rashtrasant Tukadoji Maharaj Nagpur University', 
    'Autonomous Institute', "SNDT Women's University",
    'Punyashlok Ahilyadevi Holkar Solapur University', 
    'Gondwana University'
  ];

  export const districtList = [
    'Amravati',
    'Yavatmal',
    'Buldhana',
    'Akola',
    'Washim',
    'Chhatrapati Sambhajinagar',
    'Nanded',
    'Jalna',
    'Latur',
    'Osmanabad',
    'Dharashiv',
    'Beed',
    'Parbhani',
    'Mumbai City',
    'Mumbai Suburban',
    'Raigad',
    'Ratnagiri',
    'Thane',
    'Palghar',
    'Sindhudurg',
    'Chandrapur',
    'Nagpur',
    'Wardha',
    'Bhandara',
    'Jalgaon',
    'Dhule',
    'Nashik',
    'Ahmednagar',
    'Nandurbar',
    'Pune',
    'Satara',
    'Sangli',
    'Kolhapur',
    'Solapur',
  ];

  export const branchList = ['Computer Science and Technology', 'Food Technology And Management', 'Electrical and Electronics Engineering', 'Bio Technology', 'Artificial Intelligence and Machine Learning', 'Electronics and Communication (Advanced Communication Technology)', 'Data Science', 'Mechanical Engineering', 'Data Engineering', 'Printing and Packing Technology', 'Paints Technology', 'Automobile Engineering', 'Computer Science and Engineering(Cyber Security)', 'Textile Technology', 'Computer Science and Design', 'Pharmaceuticals Chemistry and Technology', 'Manufacturing Science and Engineering', 'Chemical Engineering', 'Computer Technology', 'Agricultural Engineering', 'Robotics and Artificial Intelligence', '5G', 'Information Technology', 'Oil and Paints Technology', 'Civil Engineering and Planning', 'Fibres and Textile Processing Technology', 'Cyber Security', 'Polymer Engineering and Technology', 'Electronics Engineering', 'Textile Chemistry', 'Mechanical Engineering[Sandwich]', 'Aeronautical Engineering', 'Technical Textiles', 'Artificial Intelligence', 'Mechanical and Mechatronics Engineering (Additive Manufacturing)', 'Civil and infrastructure Engineering', 'Plastic Technology', 'Electrical and Computer Engineering', 'Mechanical & Automation Engineering', 'Bio Medical Engineering', 'Petro Chemical Engineering', 'Safety and Fire Engineering', 'Metallurgy and Material Technology', 'Electrical Engineering', 'Architectural Assistantship', 'Civil Engineering', 'Fire Engineering', 'Paper and Pulp Technology', 'Electronics Engineering ( VLSI Design and Technology)', 'Computer Science and Engineering (Artificial Intelligence and Data Science)', 'Electrical, Electronics and Power', 'Computer Science and Engineering(Data Science)', 'Oil Fats and Waxes Technology', 'Structural Engineering', 'Textile Engineering / Technology', 'Electronics and Communication Engineering', 'Food Engineering and Technology', 'Computer Science and Engineering (Cyber Security)', 'Artificial Intelligence and Data Science',
    'Oil,Oleochemicals and Surfactants Technology', 'Automation and Robotics', 'Electronics and Biomedical Engineering', 'Artificial Intelligence (AI) and Data Science', 'Computer Science and Engineering', 'Internet of Things (IoT)', 'Computer Science and Engineering(Artificial Intelligence and Machine Learning)', 'Electronics and Computer Science', 'Instrumentation Engineering', 'Mining Engineering', 'Mechanical Engineering Automobile', 'Robotics and Automation', 'VLSI', 'Computer Science and Information Technology', 'Computer Engineering', 'Electronics and Computer Engineering', 'Electronics and Communication(Advanced Communication Technology)', 'Civil and Environmental Engineering', 'Man Made Textile Technology', 'Electrical Engg[Electronics and Power]', 'Computer Engineering (Software Engineering)', 'Computer Science', 'Oil Technology', 'Plastic and Polymer Engineering', 'Surface Coating Technology', 'Dyestuff Technology', 'Computer Science and Engineering (Internet of Things and Cyber Security Including Block Chain', 'Mechatronics Engineering', 'Production Engineering[Sandwich]', 'Computer Science and Engineering (IoT)', 'Pharmaceutical and Fine Chemical Technology', 'Instrumentation and Control Engineering', 'Fashion Technology', 'Industrial IoT', 'Production Engineering', 'Computer Science and Engineering (Artificial Intelligence)', 'Computer Science and Business Systems', 'Food Technology', 'Electronics and Telecommunication Engg'
  ];

